# SPDX-License-Identifier: BSD-3-Clause
# Adapted from the X1E80100 ThinkPad T14s profile by Srinivas Kandagatla.
SectionVerb {
	EnableSequence [
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 1"
		cset "name='WSA_CODEC_DMA_RX_0 Audio Mixer MultiMedia2' 1"
	]

	Include.wsae.File "/codecs/wsa884x/two-speakers/DefaultEnableSeq.conf"
	Include.wsm1e.File "/codecs/qcom-lpass/wsa-macro/Wsa1SpeakerEnableSeq.conf"

	Value {
		TQ "HiFi"
	}
}

SectionDevice."Speaker" {
	Comment "Speaker playback"

	Include.wsmspk1e.File "/codecs/qcom-lpass/wsa-macro/Wsa1SpeakerEnableSeq.conf"
	Include.wsmspk1d.File "/codecs/qcom-lpass/wsa-macro/Wsa1SpeakerDisableSeq.conf"
	Include.wsaspk.File "/codecs/wsa884x/two-speakers/SpeakerSeq.conf"

	Value {
		PlaybackChannels 2
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},1"
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "Speakers"
	}
}

SectionDevice."Headphones" {
	Comment "Headphones playback"
	ConflictingDevice [ "HDMI0" "HDMI1" "HDMI2" ]

	Include.wcdhpe.File "/codecs/wcd938x/HeadphoneABEnableSeq.conf"
	Include.wcdhpd.File "/codecs/wcd938x/HeadphoneDisableSeq.conf"
	Include.rxmhpe.File "/codecs/qcom-lpass/rx-macro/HeadphoneEnableSeq.conf"
	Include.rxmhpd.File "/codecs/qcom-lpass/rx-macro/HeadphoneDisableSeq.conf"

	EnableSequence [
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 0"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
		PlaybackMixerElem "HP"
		JackControl "Headphone Jack"
	}
}

SectionDevice."HDMI0" {
	Comment "USB-C rear DisplayPort audio"
	ConflictingDevice [ "Headphones" "HDMI1" "HDMI2" ]

	EnableSequence [
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 0"
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		cset "name='DISPLAY_PORT_RX_0 Audio Mixer MultiMedia1' 0"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		JackControl "DP0 Jack"
	}
}

SectionDevice."HDMI1" {
	Comment "USB-C front DisplayPort audio"
	ConflictingDevice [ "Headphones" "HDMI0" "HDMI2" ]

	EnableSequence [
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 0"
		cset "name='DISPLAY_PORT_RX_1 Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		cset "name='DISPLAY_PORT_RX_1 Audio Mixer MultiMedia1' 0"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		JackControl "DP1 Jack"
	}
}

SectionDevice."HDMI2" {
	Comment "Built-in HDMI audio"
	ConflictingDevice [ "Headphones" "HDMI0" "HDMI1" ]

	EnableSequence [
		cset "name='RX_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 0"
		cset "name='DISPLAY_PORT_RX_2 Audio Mixer MultiMedia1' 1"
	]

	DisableSequence [
		cset "name='DISPLAY_PORT_RX_2 Audio Mixer MultiMedia1' 0"
	]

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId},0"
		JackControl "DP2 Jack"
	}
}
