# Generated by rust2rpm 26
%bcond_without check

# prevent library files from being installed
%global cargo_install_lib 0

# Disable debug package generation
%global debug_package %{nil}

Name:           steamos-manager
Version:        26.3.0
Release:        1%{?dist}
Summary:        SteamOS Manager daemon for running various tasks as root

License:        MIT

URL:            https://github.com/evlav/steamos-manager/
Source0:        %{url}/archive/v%{version}/%{name}-%{version}.tar.gz
Patch0:         overrides.patch

%global rust_cecd_proxy_ver 0.2.0
%global rust_linux_cec_ver 0.2.0
%global rust_linux_cec_macros_ver 0.2.0
%global rust_linux_cec_sys_ver 0.1.0
%global rust_speech_dispatcher_ver 0.16.0
%global rust_speech_dispatcher_sys_ver 0.7.0
%global rust_sysinfo_ver 0.38.4
%global rust_endi_ver 1.1.1
Source10:       https://crates.io/api/v1/crates/cecd-proxy/%{rust_cecd_proxy_ver}/download#/cecd-proxy-%{rust_cecd_proxy_ver}.tar.gz
Source11:       https://crates.io/api/v1/crates/linux-cec/%{rust_linux_cec_ver}/download#/linux-cec-%{rust_linux_cec_ver}.tar.gz
Source12:       https://crates.io/api/v1/crates/linux-cec-macros/%{rust_linux_cec_macros_ver}/download#/linux-cec-macros-%{rust_linux_cec_macros_ver}.tar.gz
Source13:       https://crates.io/api/v1/crates/linux-cec-sys/%{rust_linux_cec_sys_ver}/download#/linux-cec-sys-%{rust_linux_cec_sys_ver}.tar.gz
Source14:       https://crates.io/api/v1/crates/speech-dispatcher/%{rust_speech_dispatcher_ver}/download#/speech-dispatcher-%{rust_speech_dispatcher_ver}.tar.gz
Source15:       https://crates.io/api/v1/crates/speech-dispatcher-sys/%{rust_speech_dispatcher_sys_ver}/download#/speech-dispatcher-sys-%{rust_speech_dispatcher_sys_ver}.tar.gz
Source16:       https://crates.io/api/v1/crates/sysinfo/%{rust_sysinfo_ver}/download#/sysinfo-%{rust_sysinfo_ver}.tar.gz
Source17:       https://crates.io/api/v1/crates/endi/%{rust_endi_ver}/download#/endi-%{rust_endi_ver}.tar.gz

BuildRequires:  cargo-rpm-macros >= 26
BuildRequires:  cargo
BuildRequires:  rust-packaging
BuildRequires:  systemd-rpm-macros
BuildRequires:  clang-devel
BuildRequires:  cmake
BuildRequires:  rust
BuildRequires:  rust-std-static
BuildRequires:  pkgconfig(expat)
BuildRequires:  pkgconfig(gbm)
BuildRequires:  pkgconfig(gio-2.0)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(gobject-2.0)
BuildRequires:  pkgconfig(dbus-1)
BuildRequires:  pkgconfig(libdrm)
BuildRequires:  pkgconfig(libinput)
BuildRequires:  pkgconfig(libseat)
BuildRequires:  pkgconfig(libudev)
BuildRequires:  pkgconfig(speech-dispatcher)
BuildRequires:  pkgconfig(xkbcommon)
BuildRequires:  pkgconfig(libzstd)
BuildRequires:  desktop-file-utils
BuildRequires:  rust >= 1.85
BuildRequires:  (crate(anyhow/default) >= 1.0.0 with crate(anyhow/default) < 2.0.0~)
BuildRequires:  (crate(async-trait/default) >= 0.1.0 with crate(async-trait/default) < 0.2.0~)
BuildRequires:  (crate(bindgen/default) >= 0.54.0 with crate(bindgen/default) < 0.73.0~)
BuildRequires:  (crate(bitfield-struct/default) >= 0.12.0 with crate(bitfield-struct/default) < 0.13.0~)
BuildRequires:  (crate(clap) >= 4.5.0 with crate(clap) < 5.0.0~)
BuildRequires:  (crate(clap/derive) >= 4.5.0 with crate(clap/derive) < 5.0.0~)
BuildRequires:  (crate(clap/help) >= 4.5.0 with crate(clap/help) < 5.0.0~)
BuildRequires:  (crate(clap/std) >= 4.5.0 with crate(clap/std) < 5.0.0~)
BuildRequires:  (crate(clap/usage) >= 4.5.0 with crate(clap/usage) < 5.0.0~)
BuildRequires:  (crate(config) >= 0.15.0 with crate(config) < 0.16.0~)
BuildRequires:  (crate(config/async) >= 0.15.0 with crate(config/async) < 0.16.0~)
BuildRequires:  (crate(config/ini) >= 0.15.0 with crate(config/ini) < 0.16.0~)
BuildRequires:  (crate(config/toml) >= 0.15.0 with crate(config/toml) < 0.16.0~)
BuildRequires:  (crate(gio/default) >= 0.21.0 with crate(gio/default) < 0.22.0~)
BuildRequires:  (crate(heck/default) >= 0.5.0 with crate(heck/default) < 0.6.0~)
BuildRequires:  (crate(inotify) >= 0.11.0 with crate(inotify) < 0.12.0~)
BuildRequires:  (crate(inotify/stream) >= 0.11.0 with crate(inotify/stream) < 0.12.0~)
BuildRequires:  (crate(input-linux/default) >= 0.7.0 with crate(input-linux/default) < 0.8.0~)
BuildRequires:  (crate(itertools/default) >= 0.14.0 with crate(itertools/default) < 0.15.0~)
BuildRequires:  (crate(lazy_static/default) >= 1.0.0 with crate(lazy_static/default) < 2.0.0~)
BuildRequires:  (crate(libc/default) >= 0.2.0 with crate(libc/default) < 0.3.0~)
BuildRequires:  (crate(nix) >= 0.31.0 with crate(nix) < 0.32.0~)
BuildRequires:  (crate(nix/fs) >= 0.31.0 with crate(nix/fs) < 0.32.0~)
BuildRequires:  (crate(nix/ioctl) >= 0.31.0 with crate(nix/ioctl) < 0.32.0~)
BuildRequires:  (crate(nix/poll) >= 0.31.0 with crate(nix/poll) < 0.32.0~)
BuildRequires:  (crate(nix/signal) >= 0.31.0 with crate(nix/signal) < 0.32.0~)
BuildRequires:  (crate(nix/time) >= 0.31.0 with crate(nix/time) < 0.32.0~)
BuildRequires:  (crate(nix/user) >= 0.31.0 with crate(nix/user) < 0.32.0~)
BuildRequires:  (crate(num_enum/default) >= 0.7.0 with crate(num_enum/default) < 0.8.0~)
BuildRequires:  (crate(proc-macro2/default) >= 1.0.0 with crate(proc-macro2/default) < 2.0.0~)
BuildRequires:  (crate(quote/default) >= 1.0.0 with crate(quote/default) < 2.0.0~)
BuildRequires:  (crate(regex) >= 1.0.0 with crate(regex) < 2.0.0~)
BuildRequires:  (crate(regex/unicode-perl) >= 1.0.0 with crate(regex/unicode-perl) < 2.0.0~)
BuildRequires:  (crate(serde) >= 1.0.0 with crate(serde) < 2.0.0~)
BuildRequires:  (crate(serde/derive) >= 1.0.0 with crate(serde/derive) < 2.0.0~)
BuildRequires:  (crate(serde_json/default) >= 1.0.0 with crate(serde_json/default) < 2.0.0~)
BuildRequires:  (crate(strum/default) >= 0.28.0 with crate(strum/default) < 0.29.0~)
BuildRequires:  (crate(strum/derive) >= 0.28.0 with crate(strum/derive) < 0.29.0~)
BuildRequires:  (crate(syn/default) >= 2.0.0 with crate(syn/default) < 3.0.0~)
BuildRequires:  (crate(tempfile/default) >= 3.0.0 with crate(tempfile/default) < 4.0.0~)
BuildRequires:  (crate(thiserror/default) >= 2.0.0 with crate(thiserror/default) < 3.0.0~)
BuildRequires:  (crate(tinyvec/default) >= 1.9.0 with crate(tinyvec/default) < 2.0.0~)
BuildRequires:  (crate(tokio) >= 1.0.0 with crate(tokio) < 2.0.0~)
BuildRequires:  (crate(tokio-stream) >= 0.1.0 with crate(tokio-stream) < 0.2.0~)
BuildRequires:  (crate(tokio-util) >= 0.7.0 with crate(tokio-util) < 0.8.0~)
BuildRequires:  (crate(tokio/fs) >= 1.0.0 with crate(tokio/fs) < 2.0.0~)
BuildRequires:  (crate(tokio/io-std) >= 1.0.0 with crate(tokio/io-std) < 2.0.0~)
BuildRequires:  (crate(tokio/io-util) >= 1.0.0 with crate(tokio/io-util) < 2.0.0~)
BuildRequires:  (crate(tokio/macros) >= 1.0.0 with crate(tokio/macros) < 2.0.0~)
BuildRequires:  (crate(tokio/process) >= 1.0.0 with crate(tokio/process) < 2.0.0~)
BuildRequires:  (crate(tokio/rt-multi-thread) >= 1.0.0 with crate(tokio/rt-multi-thread) < 2.0.0~)
BuildRequires:  (crate(tokio/signal) >= 1.0.0 with crate(tokio/signal) < 2.0.0~)
BuildRequires:  (crate(tokio/sync) >= 1.0.0 with crate(tokio/sync) < 2.0.0~)
BuildRequires:  (crate(toml/default) >= 1.1.0 with crate(toml/default) < 2.0.0~)
BuildRequires:  (crate(tracing) >= 0.1.0 with crate(tracing) < 0.2.0~)
BuildRequires:  (crate(tracing-subscriber) >= 0.3.0 with crate(tracing-subscriber) < 0.4.0~)
BuildRequires:  (crate(tracing-subscriber/env-filter) >= 0.3.0 with crate(tracing-subscriber/env-filter) < 0.4.0~)
BuildRequires:  (crate(tracing-subscriber/fmt) >= 0.3.0 with crate(tracing-subscriber/fmt) < 0.4.0~)
BuildRequires:  (crate(udev/default) >= 0.9.3 with crate(udev/default) < 0.10.0~)
BuildRequires:  (crate(udev/send) >= 0.9.3 with crate(udev/send) < 0.10.0~)
BuildRequires:  (crate(udev/sync) >= 0.9.3 with crate(udev/sync) < 0.10.0~)
BuildRequires:  (crate(xdg/default) >= 3.0.0 with crate(xdg/default) < 4.0.0~)
BuildRequires:  (crate(zbus) >= 5.0.0 with crate(zbus) < 6.0.0~)
BuildRequires:  (crate(zbus/tokio) >= 5.0.0 with crate(zbus/tokio) < 6.0.0~)
BuildRequires:  (crate(zbus_xml/default) >= 5.0.0 with crate(zbus_xml/default) < 6.0.0~)


%description
SteamOS Manager is a system daemon that abstracts Steam's interactions with the
operating system.

%prep
%autosetup -n %{name}-%{version} -p1
mkdir vendor
tar -xvf %{SOURCE10} -C vendor/
tar -xvf %{SOURCE11} -C vendor/
tar -xvf %{SOURCE12} -C vendor/
tar -xvf %{SOURCE13} -C vendor/
tar -xvf %{SOURCE14} -C vendor/
tar -xvf %{SOURCE15} -C vendor/
tar -xvf %{SOURCE16} -C vendor/
tar -xvf %{SOURCE17} -C vendor/
sed -i \
    -e '/"windows\//d' \
    -e '/"objc2-core-foundation\//d' \
    -e '/"objc2-io-kit/d' \
    -e '/"dep:ntapi"/d' \
    -e '/^\[target.'\''cfg(any(target_os = "macos", target_os = "ios"))'\''.dependencies.objc2-core-foundation\]/,/^$/d' \
    -e '/^\[target.'\''cfg(any(target_os = "macos", target_os = "ios"))'\''.dependencies.objc2-io-kit\]/,/^$/d' \
    -e '/^\[target."cfg(windows)".dependencies.ntapi\]/,/^$/d' \
    -e '/^\[target."cfg(windows)".dependencies.windows\]/,/^$/d' \
    vendor/sysinfo-%{rust_sysinfo_ver}/Cargo.toml
%cargo_prep
cat >> .cargo/config.toml << EOF

[patch.crates-io]
cecd-proxy = { path = "vendor/cecd-proxy-%{rust_cecd_proxy_ver}" }
linux-cec = { path = "vendor/linux-cec-%{rust_linux_cec_ver}" }
linux-cec-macros = { path = "vendor/linux-cec-macros-%{rust_linux_cec_macros_ver}" }
linux-cec-sys = { path = "vendor/linux-cec-sys-%{rust_linux_cec_sys_ver}" }
speech-dispatcher = { path = "vendor/speech-dispatcher-%{rust_speech_dispatcher_ver}" }
speech-dispatcher-sys = { path = "vendor/speech-dispatcher-sys-%{rust_speech_dispatcher_sys_ver}" }
sysinfo = { path = "vendor/sysinfo-%{rust_sysinfo_ver}" }
endi = { path = "vendor/endi-%{rust_endi_ver}" }
EOF

%build
%cargo_build -- --package steamos-manager --bin steamos-manager
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
# Create the necessary directories
install -d -m0755 %{buildroot}%{_datadir}/dbus-1/services/
install -d -m0755 %{buildroot}%{_datadir}/dbus-1/system-services/
install -d -m0755 %{buildroot}%{_sysconfdir}/dbus-1/system.d/
install -d -m0755 %{buildroot}%{_unitdir}/
install -d -m0755 %{buildroot}%{_userunitdir}/gamescope-session-plus.service.wants/
install -d -m0755 %{buildroot}%{_libdir}/

# Install binaries
install -D -m755 target/rpm/steamos-manager %{buildroot}%{_libdir}/steamos-manager

# Install license
install -D -m644 LICENSE %{buildroot}%{_datadir}/licenses/%{name}/LICENSE

# Install systemd and dbus service files
install -m644 data/system/com.steampowered.SteamOSManager1.service %{buildroot}%{_datadir}/dbus-1/system-services/
install -m644 data/system/com.steampowered.SteamOSManager1.conf %{buildroot}%{_sysconfdir}/dbus-1/system.d/
install -m644 data/system/steamos-manager.service %{buildroot}%{_unitdir}/

# Install user-specific systemd and dbus service files
install -m644 data/user/com.steampowered.SteamOSManager1.service %{buildroot}%{_datadir}/dbus-1/services/
install -m644 data/user/steamos-manager.service %{buildroot}%{_userunitdir}/

# Create a symlink for the systemd service
ln -s ../steamos-manager.service %{buildroot}%{_userunitdir}/gamescope-session-plus.service.wants/steamos-manager.service

# Do post-installation
%post
%systemd_post steamos-manager.service

# Do before uninstallation
%preun
%systemd_preun steamos-manager.service

# Do after uninstallation
%postun
%systemd_postun_with_restart steamos-manager.service

%files
%license %{_datadir}/licenses/%{name}/LICENSE
%license LICENSE.dependencies
%doc README.md

# Binaries
%{_libdir}/steamos-manager

# DBus Service Files
%{_datadir}/dbus-1/services/com.steampowered.SteamOSManager1.service
%{_datadir}/dbus-1/system-services/com.steampowered.SteamOSManager1.service

# DBus Configuration Files
%{_sysconfdir}/dbus-1/system.d/com.steampowered.SteamOSManager1.conf

# Systemd Service Files
%{_unitdir}/steamos-manager.service
%{_userunitdir}/steamos-manager.service

# Symlink for gamescope-session
%{_userunitdir}/gamescope-session-plus.service.wants/steamos-manager.service

%changelog
%autochangelog
