monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*"
        alsa.card_name = "sof-nau8821-max"
        device.profile.description = "Speaker"
      }
    ]
    actions = {
      update-props = {
        node.description = "Steam Deck OLED Speakers"
        node.nick = "Speakers"
      }
    }
  }
]
