# This punishes software developers to not use spit locks, but affects wine
# emulation, so mute it and disable it. Just degrades performance
kernel.split_lock_mitigate=0

# Eliminate black holes if the WIFI has an ICMP black hole
net.ipv4.tcp_mtu_probing=1

# Large game libraries, launchers, and source trees can exceed default
# inotify watcher limits. Especially VS code.
fs.inotify.max_user_instances=8192
fs.inotify.max_user_watches=524288

# They can also exhaust default memory map counts
vm.max_map_count=2147483642