#!/bin/bash

if (( $# != 0 )); then
    echo "Usage: ${0##*/}" >&2
    exit 2
fi

if ! pkexec /usr/libexec/return-to-gamemode-helper; then
    echo "Failed to request Gamemode for the next login" >&2
    exit 1
fi

exec qdbus-qt6 org.kde.Shutdown /Shutdown org.kde.Shutdown.logout
