name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
permissions:
  contents: read
  packages: write

concurrency:
  group: build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 100
          token: ${{ secrets.ANATASE_READ }}
          persist-credentials: false
          submodules: recursive

      - name: Install ludos
        run: |
          python3 -m venv venv
          venv/bin/pip install --upgrade pip
          pushd ludos
          ../venv/bin/pip install -r requirements.txt
          popd

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io \
            --username "${{ github.actor }}" \
            --password-stdin

      - name: Initialize CI images
        run: venv/bin/ludos ci init anatase.yml

      - name: Prepare CI build manifest
        run: venv/bin/ludos ci prepare anatase.yml

      - name: Seed CI images
        run: venv/bin/ludos ci seed --autoremove
