[User Interface]
hidden_spokes =
    PasswordSpoke
    UserSpoke
hidden_webui_pages =
    anaconda-screen-accounts
can_change_root = False
can_change_users = False

[Storage]
default_scheme = BTRFS
btrfs_compression = zstd:1
default_partitioning =
    /     (min 1 GiB, max 70 GiB)
    /home (min 500 MiB, free 50 GiB)
    /var  (btrfs)
